config/routes.rb
SportsApp::Application.routes.draw do
  resources :teams
  resources :games
  resources :comps
  resources :tips
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "competition" => "tips#mytips"
  get "leaderboards" => "users#leaderboard"
  get "competition" => "tips#mytips"
  get "competition" => "tips#mytips"
  root :to => "users#new"
  resources :users
  resources :sessions
  get "secret" => "secret#index"
  
  
  
  match "/pages" => "pages#start"
  match "/callback" => "pages#callback"
  root :to => "tips#new"
  
  
  

end

app/models/comp.rb
class Comp < ActiveRecord::Base
   # for status : 0 = open  1 = close    2 = complete
   attr_accessible :status, :close_time, :games_attributes
   has_many   :games
   has_many   :tips
   has_many	  :users
   has_many   :usercomps
   
   accepts_nested_attributes_for :games
end

app/controllers/comps_controller.rb
class CompsController < ApplicationController
  
 # http_basic_authenticate_with :name => "admin", :password => "password"
  
  # GET /comps
  # GET /comps.json
  def index
    @comps = Comp.order("id DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comps }
    end
  end

  # GET /comps/1
  # GET /comps/1.json
  def show
    @comp = Comp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comp }
    end
  end

  # GET /comps/new
  # GET /comps/new.json
  def new
    @comp = Comp.new
	@games = Game.find_all_by_comp_id(nil)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comp }
    end
  end

  # GET /comps/1/edit
  def edit
    @comp = Comp.find(params[:id])
	respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comp }
    end
  end

  # POST /comps
  # POST /comps.json
  def create
  
    @comp = Comp.new(params[:comp])
	@games = Game.find_all_by_comp_id(nil)

    respond_to do |format|
      if @comp.save
		@games.each do |game|
			game.comp = @comp
			game.save
		end
		
        format.html { redirect_to @comp, notice: 'Comp was successfully created.' }
        format.json { render json: @comp, status: :created, location: @comp }
      else
        format.html { render action: "new" }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comps/1
  # PUT /comps/1.json
  def update
    @comp = Comp.find(params[:id])
	initial_status = @comp.status
    respond_to do |format|
      if @comp.update_attributes(params[:comp])
	    if @comp
			if initial_status == 0 and @comp.status == 2
				users = User.find_all_by_comp_id(@comp.id)
				users.each do |user|
					tips = Tip.find_all_by_user_id(user.id)
					counter = 0
					tips.each do |tip|
						if tip.team.id == tip.game.result
							counter += 1
						end
					end
					userComp = UserComp.new(:comp_id => @comp.id, :user_id => user.id, :score => counter)
					newScore = user.score + counter
					user.score = newScore
					user.save
				end
			end	
        format.html { redirect_to @comp, notice: 'Comp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /comps/1
  # DELETE /comps/1.json
  def destroy
    @comp = Comp.find(params[:id])
    @comp.destroy

    respond_to do |format|
      format.html { redirect_to comps_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/views/comps/_editform.html.erb
<%= form_for(@comp) do |f| %>
  <p>
  Comp status:
  <%= select( :comp, :status,   [['Open', 0], ['Closed', 1],['Complete', 2]]) %>
</p>

<p> This comp will be created with the following games : </p>
<% if @comp.games.count == 0 %> <p> There are no games attached to this comp</p> <% end %>
<% @comp.games.each do |game| %>
    <%= game.teamA.name %>   vs    <%= game.teamB.name %>
    <%= link_to 'Show', game %>
    <%= link_to 'Edit', edit_game_path(game) %>
    <%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %>
	</br>
 
<% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/comps/_form.html.erb
<%= nested_form_for @comp do |f| %>
  <p>
  Comp status:
  <%= select( :comp, :status,   [['Open', 0], ['Closed', 1],['Complete', 2]]) %>
  </br>
  Comp close date-time:
  <%= select_datetime %>
  </p>




<%= f.fields_for :games do |games_form| %>
  <%= games_form.text_field :id %>
  <%= games_form.link_to_remove "Remove this game" %>
<% end %>
<p><%= f.link_to_add "Add a game", :games %></p>


<p> This comp will be created with the following games : </p>
<% if @games.count == 0 %> <p> There are no games, please create games first.</p> <% end %>
<% @games.each do |game| %>
    <%= game.teamA.name %>   vs    <%= game.teamB.name %>
    <%= link_to 'Show', game %>
    <%= link_to 'Edit', edit_game_path(game) %>
    <%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %>
	</br>
 
<% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/comps/edit.html.erb
<h1>Editing Comp</h1>

<%= render 'editform' %>

<%= link_to 'Show', @comp %> |
<%= link_to 'Back', comps_path %>

app/views/comps/index.html.erb
<h1>Listing Comps</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Status</th>
    <th>Game count</th>
    <th></th>
    <th></th>
  </tr>

<% @comps.each do |comp| %>
  <tr>
    <td><%= comp.id %></td>
    <td><%= comp.status %></td>
	<td><%= comp.games.count %></td>
    <td><%= link_to 'Show', comp %></td>
    <td><%= link_to 'Edit', edit_comp_path(comp) %></td>
    <td><%= link_to 'Destroy', comp, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comp', new_comp_path %>

app/views/comps/new.html.erb
<h1>New comp</h1>

<%= render 'form' %>

<%= link_to 'Back', comps_path %>

app/views/comps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comp Id</b>
  <%= @comp.id %>
</p>

<p>
  <b>Status</b>
  <%= @comp.status %>
</p>
<p>
  <% @comp.games.each do |game| %>
  
	<%= game.id %>
    <%= game.teamA.name %>  -- vs -- <%= game.teamB.name %> 
    <%= link_to 'Show', game %>
    <%= link_to 'Edit', edit_game_path(game) %>
    <%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %>
  
<% end %>
</p>


<%= link_to 'Edit', edit_comp_path(@comp) %> |
<%= link_to 'Back', comps_path %>