config/routes.rb
SportsApp::Application.routes.draw do
  resources :teams
  resources :games
  resources :comps
  resources :tips
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "competition" => "tips#mytips"
  get "leaderboards" => "users#leaderboard"
  get "competition" => "tips#mytips"
  get "competition" => "tips#mytips"
  root :to => "users#new"
  resources :users
  resources :sessions
  get "secret" => "secret#index"
  
  
  
  match "/pages" => "pages#start"
  match "/callback" => "pages#callback"
  root :to => "tips#new"
  
  
  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  
    <li>
    <%= link_to("Competition", "/competition") %>
    </li>
    <li>
    <%= link_to("Leaderboards", "/leaderboards") %>
    </li>
	<li>
    <%= link_to('How to enter', '/howto') %>
    </li>
	<li>
    <%= link_to('T&C', '/terms') %>
    </li>
	<li>
    <%= link_to('Betin', '/betin') %>
    </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
   <div class="container">
    <header >
	<h1> Sports Tipping </h1>
    </header>
	<div class="sub-header">
	<h4> The best sports tipping comp on the internet.  Compete with your friends.  Start tipping today! </h4>
	</div>
    <div id="main" role="main">
		<div class="navbar navbar-inverse">
	   <nav class="navbar-inner">
          <%= render 'layouts/navigation' %>
      </nav>
	  </div>
	  <div class="navbar navbar-inverse">
	   <nav class="navbar-inner">
          
<ul class="nav">
  <li>
   TESTING ONLY
    </li>
    <li>
    <%= link_to("login","/login") %>
    </li>
	<li>
		<%= link_to("logout","/logout") %>
    </li>
	<li>
    <%= link_to("signup","/signup") %>
    </li>
		<li>
    <%= link_to("teams",teams_path) %>
    </li>
	<li>
    <%= link_to("games",games_path) %>
    </li>
	<li>
    <%= link_to("comps",comps_path) %>
    </li>
	

</ul>
		  
      </nav>
	  </div>
        <div class="content">
           <div class="row">

              <%= render 'layouts/messages' %>
              <%= yield %>

          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>